version: 1.0.{build}

image: Visual Studio 2022

environment:
  nodejs_version: "16"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm ci

build: off

test_script:
  - npm test

matrix:
  fast_finish: true
